### ISSUE TITLE
Error messages when cloning repo on Windows 10

### ISSUE THREAD

**Issue by joffemd** [ReasonFoundation/pension_crawler#2]
C:\>git clone https://github.com/ReasonFoundation/pension_crawler.git
Cloning into 'pension_crawler'...
remote: Counting objects: 432, done.
remote: Compressing objects: 100% (399/399), done.
Receiving objects:  93% (402/432), 1.21 GiB | 1.95 MiB/s   reused 0
Receiving objects: 100% (432/432), 1.21 GiB | 2.11 MiB/s, done.
Resolving deltas: 100% (30/30), done.
error: unable to create file data/downloads/full/176d258d079487d676e67e3a5bd121bb6905cd9b.aspx?documentid=752: Invalid argument
error: unable to create file data/downloads/full/250f4ccc75e0c2ecac748f0530a45fcac932f425.aspx?d=725050: Invalid argument
error: unable to create file data/downloads/full/3114c02b18fa3e6469b964156736486d35ffd989.aspx?Type=14&ID=2157&Inline=True: Invalid argument
error: unable to create file data/downloads/full/4f9cde67ac1f26e22173f9f162e5c91a59e78860.pdf?la=en: Invalid argument
error: unable to create file data/downloads/full/72e31079655b4d545c2d4859b4f58d3b97633a9a.pdf?la=en: Invalid argument
error: unable to create file data/downloads/full/77b1fcf36d1d1f582c9283ed3f08ecd050a382d3.pdf?1379560774: Invalid argument
error: unable to create file data/downloads/full/89de723f851291818484094deb25ba25cb493347.pdf?sfvrsn=2: Invalid argument
error: unable to create file data/downloads/full/8cd1d2782acf9e3d6b3431904d0f6b0523940710.pdf?ver=2016-06-07-133404-173: Invalid argument
error: unable to create file data/downloads/full/9c81a58390a9a6f4f55c8882248b6775906aec90.pdf?la=en: Invalid argument
error: unable to create file data/downloads/full/a9866cd860a57c4802bdf1608f2755ac58e89b7c.pdf?sfvrsn=0: Invalid argument
error: unable to create file data/downloads/full/e56e8f88ffee10b2c66f953626a6d8ede02521c5.cgi?article=2584&context=etd: Invalid argument
error: unable to create file data/downloads/full/fcacbb33b3e1664f7fbaba644355acb0e54fd9b2.aspx?documentid=714: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by tishmen** [comment]
I don't use windows, but i think it might be due to the large size of the repo (1.8 GB)
